### ISSUE TITLE
Add link to uploaded trained model weights for MT3v2

### ISSUE THREAD

**Issue by camilo-aguilar** [JulianoLagana/MT3v2#1]
Hi Juliano,

Great work exploring the combination of transformers with RFS. Would it be possible to share the trained dictionaries for object tracking? 

Thanks,
Camilo

**Comment by JulianoLagana** [comment]
Hey Camilo! Do you mean the trained model weights for MT3v2?

**Comment by camilo-aguilar** [comment]
Yes! The trained model weights!

**Comment by camilo-aguilar** [comment]
Thanks a lot!

**Comment by JulianoLagana** [comment]
I'll do it as soon as possible!

**Comment by JulianoLagana** [comment]
Solved with commit 191666e6287b0f9fadf2ff493564aae45d252922.

**Comment by soaperless** [comment]
so glad to know that the doctor is so nice to hear us
