### ISSUE TITLE
Visualizing multiple steps of output predictions

### ISSUE THREAD

**Issue by chrstrom** [JulianoLagana/MT3v2#2]
I am currently looking into plotting all predictions for a given batch/example, and I saw the reference to n_prediction_lag in [this TODO](https://github.com/JulianoLagana/MT3v2/blob/135b5274f8a0598c6abbcdfe672c19da52458838/src/util/plotting.py#L23) - I have not gotten the n_prediction_lag parameter to work for looking at output predictions at prior timesteps.

Is there any way to plot the output predictions for each timestep with the code that is currently in this repo? If not, is there any exisiting code that would allow for this?

Thanks 😄

**Comment by JulianoLagana** [comment]
This parameter has been deprecated for quite a while now, it should've been removed from the `yaml` files. Honestly I don't remember what changed since this last worked. If you want, post the error message you get when you try a nonzero value and I'll see if I can help!

**Comment by chrstrom** [comment]
Ah, no worries then. It is not triggering any errors, just not affecting the output for a given scenario. Thanks for the clarification!
