### ISSUE TITLE
I have some questions about the source code and the corresponding paper that are not clear

### ISSUE THREAD

**Issue by rrruuunnn** [JulianoLagana/MT3v2#4]
Hello, I'm sorry to bother you. My English is not very good, so I apologize in advance if I have offended you in any way.
I have read your paper carefully and also run your source code. My current understanding of your program is as follows:
First, you generate data 20 times (t=0 to 1.9) in the program at 0.1 second intervals, named batch in the program.
Then, you select the trajectory with data at t=1.9 as the true value (called labels in the program).
Finally, you compare the predicted values in the network model (named prediction in the program) with the real values (labels) and calculate the loss values to update the model parameters.
I have some questions and I would like to ask you to answer some of them.
First of all, the real values (labels) are part of the simulation data (batch) calculated by position and velocity. I don't quite understand why the real values (labels) and the simulated data (batch) have duplicated parts.
Secondly, my understanding of target tracking is to predict the target state at the current time t based on the data from the previous period (T=t-n to t-1) and correlate it with the current data. With my current understanding of the paper, the paper is predicting the state of the 16 targets with the highest probability of k at the current time from the data from the previous period to the current time (T=t-n to t). The state of the target at the current moment has already appeared in the simulation data (batch), so why do we need to predict and track it. I would like to ask you what is your understanding of target tracking.
That's what I am currently confused about. Thank you for checking this question in your busy schedule.

**Comment by JulianoLagana** [comment]
Hi! I think you're confusing the notion of a "state" and a "measurement". The measurement is a random variable which depends on the state. For example, you could have a state $x_t$ which is 2D position, where the measurement $z_t$ is a noisy version of it:

$$ z_t \sim \mathcal N(x_t^1, \Sigma^2) $$

In that case, knowing $z_t$ does not completely determine $x_t$.
